export enum Book {
  CAESARS = "Caesars",
  BETMGM = "BetMGM",
  WYNNBET = "WynnBet",
  BETRIVERS = "BetRivers",
  FANDUEL = "FanDuel",
  DRAFTKINGS = "DraftKings",
  POINTSBET = "PointsBet",
  BET365 = "Bet365",
  UNIBET = "Unibet",
  PINNACLE = "Pinnacle",
  BORGATA = "Borgata",
  TWINSPIRES = "Twinspires",
  CIRCA = "Circa",
}
